CREATE TABLE IF NOT EXISTS organizations (
    id INT PRIMARY KEY AUTO_INCREMENT,
    parent_id INT DEFAULT NULL,
    code VARCHAR(50) NOT NULL UNIQUE,
    name_th VARCHAR(255) NOT NULL,
    abbreviation VARCHAR(100) DEFAULT NULL,
    budget_allocated DECIMAL(15,2) DEFAULT 0.00,
    level INT NOT NULL DEFAULT 0 COMMENT '0=กรม, 1=กอง, 2=ฝ่าย',
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES organizations(id) ON DELETE CASCADE
);
